server:
  port: 9001

spring:
  application:
    name: qr-code-riding-zuul-server
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8763

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    qrCode-user:
      path: /micro-server-qr-code-riding/**
      serviceId: qr-code-riding-uac-service
