server:
  port: 8763

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: qr-code-riding-admin-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
