server:
  port: 9411

spring:
  application:
    name: qr-code-riding-zipkin-server
  boot:
    admin:
      client:
        url: http://localhost:8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
